language: ruby
rvm:
  - 2.0.0
env:
  - DB=sqlite
  - DB=mysql
before_script:
   - "mysql -e 'create database Rails01_test;' >/dev/null"
script:
  #- gem install debugger -v '1.6.1'
  - bundle install
  - rake db:migrate
  - rake db:test:load
  - bundle exec cucumber
before_install:
  #- gem update --system
  - gem --version
  
 
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec